name: Test Munual Workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: "L'environnement que j'ai besoin de déployer"
        required: true
        default: '/dev'

jobs:
  manual-job:
    runs-on: ubuntu-latest
    environment: CONFIGURATION DEV

    steps:
      - name: Example
        run: |
          echo "Mon exemple"
          echo "Env name: ${{github.event.inputs.Environment }}"
      - name: Github Variable
        run: echo "${{ toJSON(github)}}"
      - name: Runner Variable
        run: echo "${{ toJSON(runner)}}"
      - name: Secrets Variable
        run: echo "${{ toJSON(secrets)}}"
      - name: Env Variable
        run: echo ${{ vars.MY_API_URL }}
